name: Release

on:
  release:
    types: [published]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release AAR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-linux-androideabi
          - aarch64-linux-android
          - i686-linux-android
          - x86_64-linux-android
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: Build AAR
        run: ./gradlew --no-daemon build

      - name: Upload AAR
        uses: JasonEtco/upload-to-release@master
        with:
          args: lib/build/outputs/aar/uplink-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}