name: Release

on:
  release:
    types: [published]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release AAR
    runs-on: ubuntu-latest
    container: devduttshenoi/androidxbuild:0.1
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build AAR
        run: ./gradlew --no-daemon build

      - name: Upload AAR
        uses: JasonEtco/upload-to-release@master
        with:
          args: lib/build/outputs/aar/uplink-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}